# Generated by Django 3.2.6 on 2021-08-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210820_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='bat',
            name='relics',
            field=models.ManyToManyField(to='main_app.Relic'),
        ),
    ]
